&lt;!DOCTYPE html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
    &lt;meta charset="UTF-8"&gt;
    &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
    &lt;title&gt;Welcome to Daya&lt;/title&gt;
    &lt;style&gt;
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: #f8f9fa; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .qr-code { text-align: center; margin: 20px 0; }
        .referral-code { background-color: #e9ecef; padding: 10px; border-radius: 5px; font-family: monospace; font-size: 18px; text-align: center; margin: 20px 0; }
        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #666; }
    &lt;/style&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;div class="container"&gt;
        &lt;div class="header"&gt;
            &lt;h1&gt;Welcome to Daya, {{ $user-&gt;name }}!&lt;/h1&gt;
            &lt;p&gt;Your journey to earning through referrals starts now.&lt;/p&gt;
        &lt;/div&gt;

        &lt;div class="content"&gt;
            &lt;h2&gt;Your Referral Information&lt;/h2&gt;
            &lt;p&gt;Here's your unique referral code and QR code for sharing with potential DCDs (Digital Content Distributors):&lt;/p&gt;

            &lt;div class="referral-code"&gt;
                &lt;strong&gt;Referral Code: {{ $user-&gt;referral_code }}&lt;/strong&gt;
            &lt;/div&gt;

            &lt;div class="qr-code"&gt;
                @if($qrCodeUrl)
                    &lt;img src="{{ $qrCodeUrl }}" alt="Your QR Code" style="max-width: 200px;" /&gt;
                @else
                    &lt;p&gt;QR Code will be generated shortly.&lt;/p&gt;
                @endif
            &lt;/div&gt;

            &lt;h3&gt;How to Earn&lt;/h3&gt;
            &lt;ul&gt;
                &lt;li&gt;Share your referral code or QR code with potential DCDs&lt;/li&gt;
                &lt;li&gt;When they register using your code, you earn commissions&lt;/li&gt;
                &lt;li&gt;You'll receive 10% of all earnings generated by your referrals&lt;/li&gt;
                &lt;li&gt;Track your earnings through monthly reports sent to this email&lt;/li&gt;
            &lt;/ul&gt;

            &lt;p&gt;Start sharing and building your network today!&lt;/p&gt;

            &lt;p&gt;Best regards,&lt;br&gt;
            The Daya Team&lt;/p&gt;
        &lt;/div&gt;

        &lt;div class="footer"&gt;
            &lt;p&gt;This is an automated message. Please do not reply to this email.&lt;/p&gt;
            &lt;p&gt;© 2024 Daya. All rights reserved.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;