<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Daya</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background-color: #f8f9fa; padding: 20px; text-align: center; }
        .content { padding: 20px; }
        .qr-code { text-align: center; margin: 20px 0; }
        .referral-code { background-color: #e9ecef; padding: 10px; border-radius: 5px; font-family: monospace; font-size: 18px; text-align: center; margin: 20px 0; }
        .footer { background-color: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Welcome to Daya, {{ $user->name }}!</h1>
            <p>Your journey to earning through referrals starts now.</p>
        </div>

        <div class="content">
            <h2>Your Referral Information</h2>
            <p>Here's your unique referral code and QR code for sharing with potential DCDs (Digital Content Distributors):</p>

            <div class="referral-code">
                <strong>Referral Code: {{ $user->referral_code }}</strong>
            </div>

            <div class="qr-code">
                @if($qrCodeUrl)
                    <img src="{{ $qrCodeUrl }}" alt="Your QR Code" style="max-width: 200px;" />
                @else
                    <p>QR Code will be generated shortly.</p>
                @endif
            </div>

            @if($referrer)
            <div style="background-color: #d4edda; border: 1px solid #c3e6cb; padding: 15px; border-radius: 5px; margin: 20px 0;">
                <h3 style="color: #155724; margin-top: 0;">🎉 Referral Bonus!</h3>
                <p style="margin-bottom: 0;">You were referred by <strong>{{ $referrer->name }}</strong> ({{ ucfirst($referrer->role) }}). Welcome to the Daya family!</p>
            </div>
            @endif

            <h3>How to Earn</h3>
            <ul>
                <li>Share your referral code or QR code with potential DCDs</li>
                <li>When they register using your code, you earn commissions</li>
                <li>You'll receive 10% of all earnings generated by your referrals</li>
                <li>Track your earnings through monthly reports sent to this email</li>
            </ul>

            <p>Start sharing and building your network today!</p>

            <p>Best regards,<br>
            The Daya Team</p>
        </div>

        <div class="footer">
            <p>This is an automated message. Please do not reply to this email.</p>
            <p>© 2024 Daya. All rights reserved.</p>
        </div>
    </div>
</body>
</html>